/*
 * JS for trickTracker generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '0f717aab-f351-4aa4-aaec-666dbb5f0d0a';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "gameOfSkate",
    "location": "gameOfSkate.html"
}, {
    "name": "trickTracker",
    "location": "trickTracker.html"
}];

function trickTracker_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilelabel_7': 'trickTracker_mobilelabel_7',
        'mobilebutton_3': 'trickTracker_mobilebutton_3',
        'mobilebutton_2': 'trickTracker_mobilebutton_2'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'trickTracker';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var trickTracker_onLoad = function() {
            trickTracker_elementsExtraJS();

            trickTracker_deviceEvents();
            trickTracker_windowEvents();
            trickTracker_elementsEvents();
        };

    // screen window events


    function trickTracker_windowEvents() {

        $('#trickTracker').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function trickTracker_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function trickTracker_elementsExtraJS() {
        // screen (trickTracker) extra code

    };

    // screen elements handler


    function trickTracker_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#trickTracker_mobilefooter [name="mobilebutton_3"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('gameOfSkate', {
                        reverse: false
                    });

                }
            },
        }, '#trickTracker_mobilefooter [name="mobilebutton_3"]');
        $(document).off("click", '#trickTracker_mobilefooter [name="mobilebutton_2"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('startScreen', {
                        reverse: false
                    });

                }
            },
        }, '#trickTracker_mobilefooter [name="mobilebutton_2"]');

    };

    $(document).off("pagebeforeshow", "#trickTracker").on("pagebeforeshow", "#trickTracker", function(event, ui) {
        Apperyio.CurrentScreen = "trickTracker";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    trickTracker_onLoad();
};

$(document).off("pagecreate", "#trickTracker").on("pagecreate", "#trickTracker", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    trickTracker_js();
});